/*
Copyright 2018 Oracle and/or its affiliates. All rights reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package common

import (
	"context"

	ocice "github.com/oracle/oci-go-sdk/containerengine"
	ocicore "github.com/oracle/oci-go-sdk/core"
	ocidb "github.com/oracle/oci-go-sdk/database"
	ociid "github.com/oracle/oci-go-sdk/identity"
	ocilb "github.com/oracle/oci-go-sdk/loadbalancer"
)

// BlockStorageClientInterface defines an interface for the oci block storage client to be implemented by real and fake clients
type BlockStorageClientInterface interface {
	CreateVolume(ctx context.Context, request ocicore.CreateVolumeRequest) (response ocicore.CreateVolumeResponse, err error)
	CreateVolumeBackup(ctx context.Context, request ocicore.CreateVolumeBackupRequest) (response ocicore.CreateVolumeBackupResponse, err error)
	// CreateVolumeBackupPolicyAssignment(ctx context.Context, request ocicore.CreateVolumeBackupPolicyAssignmentRequest) (response ocicore.CreateVolumeBackupPolicyAssignmentResponse, err error)
	// DeleteBootVolume(ctx context.Context, request ocicore.DeleteBootVolumeRequest) (response ocicore.DeleteBootVolumeResponse, err error)
	DeleteVolume(ctx context.Context, request ocicore.DeleteVolumeRequest) (response ocicore.DeleteVolumeResponse, err error)
	DeleteVolumeBackup(ctx context.Context, request ocicore.DeleteVolumeBackupRequest) (response ocicore.DeleteVolumeBackupResponse, err error)
	// DeleteVolumeBackupPolicyAssignment(ctx context.Context, request ocicore.DeleteVolumeBackupPolicyAssignmentRequest) (response ocicore.DeleteVolumeBackupPolicyAssignmentResponse, err error)
	GetBootVolume(ctx context.Context, request ocicore.GetBootVolumeRequest) (response ocicore.GetBootVolumeResponse, err error)
	GetVolume(ctx context.Context, request ocicore.GetVolumeRequest) (response ocicore.GetVolumeResponse, err error)
	GetVolumeBackup(ctx context.Context, request ocicore.GetVolumeBackupRequest) (response ocicore.GetVolumeBackupResponse, err error)
	// GetVolumeBackupPolicy(ctx context.Context, request ocicore.GetVolumeBackupPolicyRequest) (response ocicore.GetVolumeBackupPolicyResponse, err error)
	// GetVolumeBackupPolicyAssetAssignment(ctx context.Context, request ocicore.GetVolumeBackupPolicyAssetAssignmentRequest) (response ocicore.GetVolumeBackupPolicyAssetAssignmentResponse, err error)
	// GetVolumeBackupPolicyAssignment(ctx context.Context, request ocicore.GetVolumeBackupPolicyAssignmentRequest) (response ocicore.GetVolumeBackupPolicyAssignmentResponse, err error)
	// ListBootVolumes(ctx context.Context, request ocicore.ListBootVolumesRequest) (response ocicore.ListBootVolumesResponse, err error)
	// ListVolumeBackupPolicies(ctx context.Context, request ocicore.ListVolumeBackupPoliciesRequest) (response ocicore.ListVolumeBackupPoliciesResponse, err error)
	// ListVolumeBackups(ctx context.Context, request ocicore.ListVolumeBackupsRequest) (response ocicore.ListVolumeBackupsResponse, err error)
	// ListVolumes(ctx context.Context, request ocicore.ListVolumesRequest) (response ocicore.ListVolumesResponse, err error)
	// UpdateBootVolume(ctx context.Context, request ocicore.UpdateBootVolumeRequest) (response ocicore.UpdateBootVolumeResponse, err error)
	UpdateVolume(ctx context.Context, request ocicore.UpdateVolumeRequest) (response ocicore.UpdateVolumeResponse, err error)
	UpdateVolumeBackup(ctx context.Context, request ocicore.UpdateVolumeBackupRequest) (response ocicore.UpdateVolumeBackupResponse, err error)
}

// ComputeClientInterface defines an interface for the oci compute client to be implemented by real and fake clients
type ComputeClientInterface interface {
	// AttachBootVolume(ctx context.Context, reqiest ocicore.AttachBootVolumeRequest) (response ocicore.AttachBootVolumeResponse, err error)
	// AttachVnic(ctx context.Context, reqiest ocicore.AttachVnicRequest) (response ocicore.AttachVnicResponse, err error)
	AttachVolume(ctx context.Context, reqiest ocicore.AttachVolumeRequest) (response ocicore.AttachVolumeResponse, err error)
	// CaptureConsoleHistory(ctx context.Context, reqiest ocicore.CaptureConsoleHistoryRequest) (response ocicore.CaptureConsoleHistoryResponse, err error)
	// CreateImage(ctx context.Context, reqiest ocicore.CreateImageRequest) (response ocicore.CreateImageResponse, err error)
	// CreateInstanceConsoleConnection(ctx context.Context, reqiest ocicore.CreateInstanceConsoleConnectionRequest) (response ocicore.CreateInstanceConsoleConnectionResponse, err error)
	// DeleteConsoleHistory(ctx context.Context, reqiest ocicore.DeleteConsoleHistoryRequest) (response ocicore.DeleteConsoleHistoryResponse, err error)
	// DeleteImage(ctx context.Context, reqiest ocicore.DeleteImageRequest) (response ocicore.DeleteImageResponse, err error)
	// DeleteInstanceConsoleConnection(ctx context.Context, reqiest ocicore.DeleteInstanceConsoleConnectionRequest) (response ocicore.DeleteInstanceConsoleConnectionResponse, err error)
	// DetachBootVolume(ctx context.Context, reqiest ocicore.DetachBootVolumeRequest) (response ocicore.DetachBootVolumeResponse, err error)
	// DetachVnic(ctx context.Context, reqiest ocicore.DetachVnicRequest) (response ocicore.DetachVnicResponse, err error)
	DetachVolume(ctx context.Context, reqiest ocicore.DetachVolumeRequest) (response ocicore.DetachVolumeResponse, err error)
	// ExportImage(ctx context.Context, reqiest ocicore.ExportImageRequest) (response ocicore.ExportImageResponse, err error)
	// GetBootVolumeAttachment(ctx context.Context, reqiest ocicore.GetBootVolumeAttachmentRequest) (response ocicore.GetBootVolumeAttachmentResponse, err error)
	// GetConsoleHistory(ctx context.Context, reqiest ocicore.GetConsoleHistoryRequest) (response ocicore.GetConsoleHistoryResponse, err error)
	// GetConsoleHistoryContent(ctx context.Context, reqiest ocicore.GetConsoleHistoryContentRequest) (response ocicore.GetConsoleHistoryContentResponse, err error)
	// GetImage(ctx context.Context, reqiest ocicore.GetImageRequest) (response ocicore.GetImageResponse, err error)
	GetInstance(ctx context.Context, reqiest ocicore.GetInstanceRequest) (response ocicore.GetInstanceResponse, err error)
	// GetInstanceConsoleConnection(ctx context.Context, reqiest ocicore.GetInstanceConsoleConnectionRequest) (response ocicore.GetInstanceConsoleConnectionResponse, err error)
	// GetVnicAttachment(ctx context.Context, reqiest ocicore.GetVnicAttachmentRequest) (response ocicore.GetVnicAttachmentResponse, err error)
	GetVolumeAttachment(ctx context.Context, reqiest ocicore.GetVolumeAttachmentRequest) (response ocicore.GetVolumeAttachmentResponse, err error)
	// GetWindowsInstanceInitialCredentials(ctx context.Context, reqiest ocicore.GetWindowsInstanceInitialCredentialsRequest) (response ocicore.GetWindowsInstanceInitialCredentialsResponse, err error)
	InstanceAction(ctx context.Context, reqiest ocicore.InstanceActionRequest) (response ocicore.InstanceActionResponse, err error)
	LaunchInstance(ctx context.Context, reqiest ocicore.LaunchInstanceRequest) (response ocicore.LaunchInstanceResponse, err error)
	ListBootVolumeAttachments(ctx context.Context, reqiest ocicore.ListBootVolumeAttachmentsRequest) (response ocicore.ListBootVolumeAttachmentsResponse, err error)
	ListVnicAttachments(ctx context.Context, reqiest ocicore.ListVnicAttachmentsRequest) (response ocicore.ListVnicAttachmentsResponse, err error)
	// ListVolumeAttachments(ctx context.Context, reqiest ocicore.ListVolumeAttachmentsRequest) (response ocicore.ListVolumeAttachmentsResponse, err error)
	// ListConsoleHistories(ctx context.Context, reqiest ocicore.ListConsoleHistoriesRequest) (response ocicore.ListConsoleHistoriesResponse, err error)
	ListImages(ctx context.Context, reqiest ocicore.ListImagesRequest) (response ocicore.ListImagesResponse, err error)
	// ListInstanceConsoleConnections(ctx context.Context, reqiest ocicore.ListInstanceConsoleConnectionsRequest) (response ocicore.ListInstanceConsoleConnectionsResponse, err error)
	// ListInstances(ctx context.Context, reqiest ocicore.ListInstancesRequest) (response ocicore.ListInstancesResponse, err error)
	ListShapes(ctx context.Context, reqiest ocicore.ListShapesRequest) (response ocicore.ListShapesResponse, err error)
	TerminateInstance(ctx context.Context, reqiest ocicore.TerminateInstanceRequest) (response ocicore.TerminateInstanceResponse, err error)
	// UpdateConsoleHistory(ctx context.Context, reqiest ocicore.UpdateConsoleHistoryRequest) (response ocicore.UpdateConsoleHistoryResponse, err error)
	// UpdateImage(ctx context.Context, reqiest ocicore.UpdateImageRequest) (response ocicore.UpdateImageResponse, err error)
	UpdateInstance(ctx context.Context, reqiest ocicore.UpdateInstanceRequest) (response ocicore.UpdateInstanceResponse, err error)
}

// ContainerEngineClientInterface defines an interface for the oci ContainerEngine client to be implemented by real and fake clients
type ContainerEngineClientInterface interface {
	CreateCluster(ctx context.Context, request ocice.CreateClusterRequest) (response ocice.CreateClusterResponse, err error)
	CreateKubeconfig(ctx context.Context, request ocice.CreateKubeconfigRequest) (response ocice.CreateKubeconfigResponse, err error)
	CreateNodePool(ctx context.Context, request ocice.CreateNodePoolRequest) (response ocice.CreateNodePoolResponse, err error)
	DeleteCluster(ctx context.Context, request ocice.DeleteClusterRequest) (response ocice.DeleteClusterResponse, err error)
	DeleteNodePool(ctx context.Context, request ocice.DeleteNodePoolRequest) (response ocice.DeleteNodePoolResponse, err error)
	// DeleteWorkRequest(ctx context.Context, request ocice.DeleteWorkRequestRequest) (response ocice.DeleteWorkRequestResponse, err error)
	GetCluster(ctx context.Context, request ocice.GetClusterRequest) (response ocice.GetClusterResponse, err error)
	// GetClusterOptions(ctx context.Context, request ocice.GetClusterOptionsRequest) (response ocice.GetClusterOptionsResponse, err error)
	GetNodePool(ctx context.Context, request ocice.GetNodePoolRequest) (response ocice.GetNodePoolResponse, err error)
	// GetNodePoolOptions(ctx context.Context, request ocice.GetNodePoolOptionsRequest) (response ocice.GetNodePoolOptionsResponse, err error)
	GetWorkRequest(ctx context.Context, request ocice.GetWorkRequestRequest) (response ocice.GetWorkRequestResponse, err error)
	ListClusters(ctx context.Context, request ocice.ListClustersRequest) (response ocice.ListClustersResponse, err error)
	ListNodePools(ctx context.Context, request ocice.ListNodePoolsRequest) (response ocice.ListNodePoolsResponse, err error)
	// ListWorkRequestErrors(ctx context.Context, request ocice.ListWorkRequestErrorsRequest) (response ocice.ListWorkRequestErrorsResponse, err error)
	// ListWorkRequestLogs(ctx context.Context, request ocice.ListWorkRequestLogsRequest) (response ocice.ListWorkRequestLogsResponse, err error)
	// ListWorkRequests(ctx context.Context, request ocice.ListWorkRequestsRequest) (response ocice.ListWorkRequestsResponse, err error)
	UpdateCluster(ctx context.Context, request ocice.UpdateClusterRequest) (response ocice.UpdateClusterResponse, err error)
	UpdateNodePool(ctx context.Context, request ocice.UpdateNodePoolRequest) (response ocice.UpdateNodePoolResponse, err error)
}

// ContainerEngineClientInterface defines an interface for the oci ContainerEngine client to be implemented by real and fake clients
type DatabaseClientInterface interface {
	// CompleteExternalBackupJob(ctx context.Context, request CompleteExternalBackupJobRequest) (response CompleteExternalBackupJobResponse, err error)
	// CreateAutonomousDataWarehouse(ctx context.Context, request CreateAutonomousDataWarehouseRequest) (response CreateAutonomousDataWarehouseResponse, err error)
	// CreateAutonomousDataWarehouseBackup(ctx context.Context, request CreateAutonomousDataWarehouseBackupRequest) (response CreateAutonomousDataWarehouseBackupResponse, err error)
	CreateAutonomousDatabase(ctx context.Context, request ocidb.CreateAutonomousDatabaseRequest) (response ocidb.CreateAutonomousDatabaseResponse, err error)
	// CreateAutonomousDatabaseBackup(ctx context.Context, request CreateAutonomousDatabaseBackupRequest) (response CreateAutonomousDatabaseBackupResponse, err error)
	// CreateBackup(ctx context.Context, request CreateBackupRequest) (response CreateBackupResponse, err error)
	// CreateDataGuardAssociation(ctx context.Context, request CreateDataGuardAssociationRequest) (response CreateDataGuardAssociationResponse, err error)
	// CreateDbHome(ctx context.Context, request CreateDbHomeRequest) (response CreateDbHomeResponse, err error)
	// CreateExternalBackupJob(ctx context.Context, request CreateExternalBackupJobRequest) (response CreateExternalBackupJobResponse, err error)
	// DbNodeAction(ctx context.Context, request DbNodeActionRequest) (response DbNodeActionResponse, err error)
	// DeleteAutonomousDataWarehouse(ctx context.Context, request DeleteAutonomousDataWarehouseRequest) (response DeleteAutonomousDataWarehouseResponse, err error)
	DeleteAutonomousDatabase(ctx context.Context, request ocidb.DeleteAutonomousDatabaseRequest) (response ocidb.DeleteAutonomousDatabaseResponse, err error)
	// DeleteBackup(ctx context.Context, request DeleteBackupRequest) (response DeleteBackupResponse, err error)
	// DeleteDbHome(ctx context.Context, request DeleteDbHomeRequest) (response DeleteDbHomeResponse, err error)
	// FailoverDataGuardAssociation(ctx context.Context, request FailoverDataGuardAssociationRequest) (response FailoverDataGuardAssociationResponse, err error)
	// GenerateAutonomousDataWarehouseWallet(ctx context.Context, request GenerateAutonomousDataWarehouseWalletRequest) (response GenerateAutonomousDataWarehouseWalletResponse, err error)
	GenerateAutonomousDatabaseWallet(ctx context.Context, request ocidb.GenerateAutonomousDatabaseWalletRequest) (response ocidb.GenerateAutonomousDatabaseWalletResponse, err error)
	// GetAutonomousDataWarehouse(ctx context.Context, request GetAutonomousDataWarehouseRequest) (response GetAutonomousDataWarehouseResponse, err error)
	// GetAutonomousDataWarehouseBackup(ctx context.Context, request GetAutonomousDataWarehouseBackupRequest) (response GetAutonomousDataWarehouseBackupResponse, err error)
	GetAutonomousDatabase(ctx context.Context, request ocidb.GetAutonomousDatabaseRequest) (response ocidb.GetAutonomousDatabaseResponse, err error)
	// GetAutonomousDatabaseBackup(ctx context.Context, request GetAutonomousDatabaseBackupRequest) (response GetAutonomousDatabaseBackupResponse, err error)
	// GetBackup(ctx context.Context, request GetBackupRequest) (response GetBackupResponse, err error)
	// GetDataGuardAssociation(ctx context.Context, request GetDataGuardAssociationRequest) (response GetDataGuardAssociationResponse, err error)
	// GetDatabase(ctx context.Context, request GetDatabaseRequest) (response GetDatabaseResponse, err error)
	// GetDbHome(ctx context.Context, request GetDbHomeRequest) (response GetDbHomeResponse, err error)
	// GetDbHomePatch(ctx context.Context, request GetDbHomePatchRequest) (response GetDbHomePatchResponse, err error)
	// GetDbHomePatchHistoryEntry(ctx context.Context, request GetDbHomePatchHistoryEntryRequest) (response GetDbHomePatchHistoryEntryResponse, err error)
	// GetDbNode(ctx context.Context, request GetDbNodeRequest) (response GetDbNodeResponse, err error)
	// GetDbSystem(ctx context.Context, request GetDbSystemRequest) (response GetDbSystemResponse, err error)
	// GetDbSystemPatch(ctx context.Context, request GetDbSystemPatchRequest) (response GetDbSystemPatchResponse, err error)
	// GetDbSystemPatchHistoryEntry(ctx context.Context, request GetDbSystemPatchHistoryEntryRequest) (response GetDbSystemPatchHistoryEntryResponse, err error)
	// GetExternalBackupJob(ctx context.Context, request GetExternalBackupJobRequest) (response GetExternalBackupJobResponse, err error)
	// LaunchDbSystem(ctx context.Context, request LaunchDbSystemRequest) (response LaunchDbSystemResponse, err error)
	// ListAutonomousDataWarehouseBackups(ctx context.Context, request ListAutonomousDataWarehouseBackupsRequest) (response ListAutonomousDataWarehouseBackupsResponse, err error)
	// ListAutonomousDataWarehouses(ctx context.Context, request ListAutonomousDataWarehousesRequest) (response ListAutonomousDataWarehousesResponse, err error)
	// ListAutonomousDatabaseBackups(ctx context.Context, request ListAutonomousDatabaseBackupsRequest) (response ListAutonomousDatabaseBackupsResponse, err error)
	ListAutonomousDatabases(ctx context.Context, request ocidb.ListAutonomousDatabasesRequest) (response ocidb.ListAutonomousDatabasesResponse, err error)
	// ListBackups(ctx context.Context, request ListBackupsRequest) (response ListBackupsResponse, err error)
	// ListDataGuardAssociations(ctx context.Context, request ListDataGuardAssociationsRequest) (response ListDataGuardAssociationsResponse, err error)
	// ListDatabases(ctx context.Context, request ListDatabasesRequest) (response ListDatabasesResponse, err error)
	// ListDbHomePatchHistoryEntries(ctx context.Context, request ListDbHomePatchHistoryEntriesRequest) (response ListDbHomePatchHistoryEntriesResponse, err error)
	// ListDbHomePatches(ctx context.Context, request ListDbHomePatchesRequest) (response ListDbHomePatchesResponse, err error)
	// ListDbHomes(ctx context.Context, request ListDbHomesRequest) (response ListDbHomesResponse, err error)
	// ListDbNodes(ctx context.Context, request ListDbNodesRequest) (response ListDbNodesResponse, err error)
	// ListDbSystemPatchHistoryEntries(ctx context.Context, request ListDbSystemPatchHistoryEntriesRequest) (response ListDbSystemPatchHistoryEntriesResponse, err error)
	// ListDbSystemPatches(ctx context.Context, request ListDbSystemPatchesRequest) (response ListDbSystemPatchesResponse, err error)
	// ListDbSystemShapes(ctx context.Context, request ListDbSystemShapesRequest) (response ListDbSystemShapesResponse, err error)
	// ListDbSystems(ctx context.Context, request ListDbSystemsRequest) (response ListDbSystemsResponse, err error)
	// ListDbVersions(ctx context.Context, request ListDbVersionsRequest) (response ListDbVersionsResponse, err error)
	// ReinstateDataGuardAssociation(ctx context.Context, request ReinstateDataGuardAssociationRequest) (response ReinstateDataGuardAssociationResponse, err error)
	// RestoreAutonomousDataWarehouse(ctx context.Context, request RestoreAutonomousDataWarehouseRequest) (response RestoreAutonomousDataWarehouseResponse, err error)
	// RestoreAutonomousDatabase(ctx context.Context, request RestoreAutonomousDatabaseRequest) (response RestoreAutonomousDatabaseResponse, err error)
	// RestoreDatabase(ctx context.Context, request RestoreDatabaseRequest) (response RestoreDatabaseResponse, err error)
	// StartAutonomousDataWarehouse(ctx context.Context, request StartAutonomousDataWarehouseRequest) (response StartAutonomousDataWarehouseResponse, err error)
	StartAutonomousDatabase(ctx context.Context, request ocidb.StartAutonomousDatabaseRequest) (response ocidb.StartAutonomousDatabaseResponse, err error)
	// StopAutonomousDataWarehouse(ctx context.Context, request StopAutonomousDataWarehouseRequest) (response StopAutonomousDataWarehouseResponse, err error)
	StopAutonomousDatabase(ctx context.Context, request ocidb.StopAutonomousDatabaseRequest) (response ocidb.StopAutonomousDatabaseResponse, err error)
	// SwitchoverDataGuardAssociation(ctx context.Context, request SwitchoverDataGuardAssociationRequest) (response SwitchoverDataGuardAssociationResponse, err error)
	// TerminateDbSystem(ctx context.Context, request TerminateDbSystemRequest) (response TerminateDbSystemResponse, err error)
	// UpdateAutonomousDataWarehouse(ctx context.Context, request UpdateAutonomousDataWarehouseRequest) (response UpdateAutonomousDataWarehouseResponse, err error)
	UpdateAutonomousDatabase(ctx context.Context, request ocidb.UpdateAutonomousDatabaseRequest) (response ocidb.UpdateAutonomousDatabaseResponse, err error)
	// UpdateDatabase(ctx context.Context, request UpdateDatabaseRequest) (response UpdateDatabaseResponse, err error)
	// UpdateDbHome(ctx context.Context, request UpdateDbHomeRequest) (response UpdateDbHomeResponse, err error)
	// UpdateDbSystem(ctx context.Context, request UpdateDbSystemRequest) (response UpdateDbSystemResponse, err error)
}

// IdentityClientInterface defines an interface for the oci identity client to be implemented by real and fake clients
type IdentityClientInterface interface {
	GetCompartment(ctx context.Context, request ociid.GetCompartmentRequest) (response ociid.GetCompartmentResponse, err error)
	// AddUserToGroup(ctx context.Context, request ociid.AddUserToGroupRequest) (response ociid.AddUserToGroupResponse, err error)
	CreateCompartment(ctx context.Context, request ociid.CreateCompartmentRequest) (response ociid.CreateCompartmentResponse, err error)
	// CreateCustomerSecretKey(ctx context.Context, request ociid.CreateCustomerSecretKeyRequest) (response ociid.CreateCustomerSecretKeyResponse, err error)
	// CreateDynamicGroup(ctx context.Context, request ociid.CreateDynamicGroupRequest) (response ociid.CreateDynamicGroupResponse, err error)
	// CreateGroup(ctx context.Context, request ociid.CreateGroupRequest) (response ociid.CreateGroupResponse, err error)
	// CreateIdentityProvider(ctx context.Context, request ociid.CreateIdentityProviderRequest) (response ociid.CreateIdentityProviderResponse, err error)
	// CreateIdpGroupMapping(ctx context.Context, request ociid.CreateIdpGroupMappingRequest) (response ociid.CreateIdpGroupMappingResponse, err error)
	// CreateOrResetUIPassword(ctx context.Context, request ociid.CreateOrResetUIPasswordRequest) (response ociid.CreateOrResetUIPasswordResponse, err error)
	CreatePolicy(ctx context.Context, request ociid.CreatePolicyRequest) (response ociid.CreatePolicyResponse, err error)
	// CreateRegionSubscription(ctx context.Context, request ociid.CreateRegionSubscriptionRequest) (response ociid.CreateRegionSubscriptionResponse, err error)
	// CreateSmtpCredential(ctx context.Context, request ociid.CreateSmtpCredentialRequest) (response ociid.CreateSmtpCredentialResponse, err error)
	// CreateSwiftPassword(ctx context.Context, request ociid.CreateSwiftPasswordRequest) (response ociid.CreateSwiftPasswordResponse, err error)
	// CreateTag(ctx context.Context, request ociid.CreateTagRequest) (response ociid.CreateTagResponse, err error)
	// CreateTagNamespace(ctx context.Context, request ociid.CreateTagNamespaceRequest) (response ociid.CreateTagNamespaceResponse, err error)
	// CreateUser(ctx context.Context, request ociid.CreateUserRequest) (response ociid.CreateUserResponse, err error)
	// DeleteApiKey(ctx context.Context, request ociid.DeleteApiKeyRequest) (response ociid.DeleteApiKeyResponse, err error)
	DeleteCompartment(ctx context.Context, request ociid.DeleteCompartmentRequest) (response ociid.DeleteCompartmentResponse, err error)
	// DeleteCustomerSecretKey(ctx context.Context, request ociid.DeleteCustomerSecretKeyRequest) (response ociid.DeleteCustomerSecretKeyResponse, err error)
	// DeleteDynamicGroup(ctx context.Context, request ociid.DeleteDynamicGroupRequest) (response ociid.DeleteDynamicGroupResponse, err error)
	// DeleteGroup(ctx context.Context, request ociid.DeleteGroupRequest) (response ociid.DeleteGroupResponse, err error)
	// DeleteIdentityProvider(ctx context.Context, request ociid.DeleteIdentityProviderRequest) (response ociid.DeleteIdentityProviderResponse, err error)
	// DeleteIdpGroupMapping(ctx context.Context, request ociid.DeleteIdpGroupMappingRequest) (response ociid.DeleteIdpGroupMappingResponse, err error)
	DeletePolicy(ctx context.Context, request ociid.DeletePolicyRequest) (response ociid.DeletePolicyResponse, err error)
	// DeleteSmtpCredential(ctx context.Context, request ociid.DeleteSmtpCredentialRequest) (response ociid.DeleteSmtpCredentialResponse, err error)
	// DeleteSwiftPassword(ctx context.Context, request ociid.DeleteSwiftPasswordRequest) (response ociid.DeleteSwiftPasswordResponse, err error)
	// DeleteUser(ctx context.Context, request ociid.DeleteUserRequest) (response ociid.DeleteUserResponse, err error)
	// GetDynamicGroup(ctx context.Context, request ociid.GetDynamicGroupRequest) (response ociid.GetDynamicGroupResponse, err error)
	// GetGroup(ctx context.Context, request ociid.GetGroupRequest) (response ociid.GetGroupResponse, err error)
	// GetIdentityProvider(ctx context.Context, request ociid.GetIdentityProviderRequest) (response ociid.GetIdentityProviderResponse, err error)
	// GetIdpGroupMapping(ctx context.Context, request ociid.GetIdpGroupMappingRequest) (response ociid.GetIdpGroupMappingResponse, err error)
	GetPolicy(ctx context.Context, request ociid.GetPolicyRequest) (response ociid.GetPolicyResponse, err error)
	// GetTag(ctx context.Context, request ociid.GetTagRequest) (response ociid.GetTagResponse, err error)
	// GetTagNamespace(ctx context.Context, request ociid.GetTagNamespaceRequest) (response ociid.GetTagNamespaceResponse, err error)
	// GetTenancy(ctx context.Context, request ociid.GetTenancyRequest) (response ociid.GetTenancyResponse, err error)
	// GetUser(ctx context.Context, request ociid.GetUserRequest) (response ociid.GetUserResponse, err error)
	// GetUserGroupMembership(ctx context.Context, request ociid.GetUserGroupMembershipRequest) (response ociid.GetUserGroupMembershipResponse, err error)
	// ListApiKeys(ctx context.Context, request ociid.ListApiKeysRequest) (response ociid.ListApiKeysResponse, err error)
	ListAvailabilityDomains(ctx context.Context, request ociid.ListAvailabilityDomainsRequest) (response ociid.ListAvailabilityDomainsResponse, err error)
	ListCompartments(ctx context.Context, request ociid.ListCompartmentsRequest) (response ociid.ListCompartmentsResponse, err error)
	// ListCustomerSecretKeys(ctx context.Context, request ociid.ListCustomerSecretKeysRequest) (response ociid.ListCustomerSecretKeysResponse, err error)
	// ListDynamicGroups(ctx context.Context, request ociid.ListDynamicGroupsRequest) (response ociid.ListDynamicGroupsResponse, err error)
	// ListGroups(ctx context.Context, request ociid.ListGroupsRequest) (response ociid.ListGroupsResponse, err error)
	// ListIdentityProviders(ctx context.Context, request ociid.ListIdentityProvidersRequest) (response ociid.ListIdentityProvidersResponse, err error)
	// ListIdpGroupMappings(ctx context.Context, request ociid.ListIdpGroupMappingsRequest) (response ociid.ListIdpGroupMappingsResponse, err error)
	// ListPolicies(ctx context.Context, request ociid.ListPoliciesRequest) (response ociid.ListPoliciesResponse, err error)
	// ListRegionSubscriptions(ctx context.Context, request ociid.ListRegionSubscriptionsRequest) (response ociid.ListRegionSubscriptionsResponse, err error)
	// ListRegions(ctx context.Context) (response ociid.ListRegionsResponse, err error)
	// ListSmtpCredentials(ctx context.Context, request ociid.ListSmtpCredentialsRequest) (response ociid.ListSmtpCredentialsResponse, err error)
	// ListSwiftPasswords(ctx context.Context, request ociid.ListSwiftPasswordsRequest) (response ociid.ListSwiftPasswordsResponse, err error)
	// ListTagNamespaces(ctx context.Context, request ociid.ListTagNamespacesRequest) (response ociid.ListTagNamespacesResponse, err error)
	// ListTags(ctx context.Context, request ociid.ListTagsRequest) (response ociid.ListTagsResponse, err error)
	// ListUserGroupMemberships(ctx context.Context, request ociid.ListUserGroupMembershipsRequest) (response ociid.ListUserGroupMembershipsResponse, err error)
	// ListUsers(ctx context.Context, request ociid.ListUsersRequest) (response ociid.ListUsersResponse, err error)
	// RemoveUserFromGroup(ctx context.Context, request ociid.RemoveUserFromGroupRequest) (response ociid.RemoveUserFromGroupResponse, err error)
	// UpdateCompartment(ctx context.Context, request ociid.UpdateCompartmentRequest) (response ociid.UpdateCompartmentResponse, err error)
	// UpdateCustomerSecretKey(ctx context.Context, request ociid.UpdateCustomerSecretKeyRequest) (response ociid.UpdateCustomerSecretKeyResponse, err error)
	// UpdateDynamicGroup(ctx context.Context, request ociid.UpdateDynamicGroupRequest) (response ociid.UpdateDynamicGroupResponse, err error)
	// UpdateGroup(ctx context.Context, request ociid.UpdateGroupRequest) (response ociid.UpdateGroupResponse, err error)
	// UpdateIdentityProvider(ctx context.Context, request ociid.UpdateIdentityProviderRequest) (response ociid.UpdateIdentityProviderResponse, err error)
	// UpdateIdpGroupMapping(ctx context.Context, request ociid.UpdateIdpGroupMappingRequest) (response ociid.UpdateIdpGroupMappingResponse, err error)
	UpdatePolicy(ctx context.Context, request ociid.UpdatePolicyRequest) (response ociid.UpdatePolicyResponse, err error)
	// UpdateSmtpCredential(ctx context.Context, request ociid.UpdateSmtpCredentialRequest) (response ociid.UpdateSmtpCredentialResponse, err error)
	// UpdateSwiftPassword(ctx context.Context, request ociid.UpdateSwiftPasswordRequest) (response ociid.UpdateSwiftPasswordResponse, err error)
	// UpdateTag(ctx context.Context, request ociid.UpdateTagRequest) (response ociid.UpdateTagResponse, err error)
	// UpdateTagNamespace(ctx context.Context, request ociid.UpdateTagNamespaceRequest) (response ociid.UpdateTagNamespaceResponse, err error)
	// UpdateUser(ctx context.Context, request ociid.UpdateUserRequest) (response ociid.UpdateUserResponse, err error)
	// UpdateUserState(ctx context.Context, request ociid.UpdateUserStateRequest) (response ociid.UpdateUserStateResponse, err error)
	// UploadApiKey(ctx context.Context, request ociid.UploadApiKeyRequest) (response ociid.UploadApiKeyResponse, err error)
}

// LoadBalancerClientInterface defines an interface for the oci load balancer client to be implemented by real and fake clients
type LoadBalancerClientInterface interface {
	CreateBackend(ctx context.Context, request ocilb.CreateBackendRequest) (response ocilb.CreateBackendResponse, err error)
	CreateBackendSet(ctx context.Context, request ocilb.CreateBackendSetRequest) (response ocilb.CreateBackendSetResponse, err error)
	CreateCertificate(ctx context.Context, request ocilb.CreateCertificateRequest) (response ocilb.CreateCertificateResponse, err error)
	CreateListener(ctx context.Context, request ocilb.CreateListenerRequest) (response ocilb.CreateListenerResponse, err error)
	CreateLoadBalancer(ctx context.Context, request ocilb.CreateLoadBalancerRequest) (response ocilb.CreateLoadBalancerResponse, err error)
	// CreatePathRouteSet(ctx context.Context, request ocilb.CreatePathRouteSetRequest) (response ocilb.CreatePathRouteSetResponse, err error)
	DeleteBackend(ctx context.Context, request ocilb.DeleteBackendRequest) (response ocilb.DeleteBackendResponse, err error)
	DeleteBackendSet(ctx context.Context, request ocilb.DeleteBackendSetRequest) (response ocilb.DeleteBackendSetResponse, err error)
	DeleteCertificate(ctx context.Context, request ocilb.DeleteCertificateRequest) (response ocilb.DeleteCertificateResponse, err error)
	DeleteListener(ctx context.Context, request ocilb.DeleteListenerRequest) (response ocilb.DeleteListenerResponse, err error)
	DeleteLoadBalancer(ctx context.Context, request ocilb.DeleteLoadBalancerRequest) (response ocilb.DeleteLoadBalancerResponse, err error)
	// DeletePathRouteSet(ctx context.Context, request ocilb.DeletePathRouteSetRequest) (response ocilb.DeletePathRouteSetResponse, err error)
	GetBackend(ctx context.Context, request ocilb.GetBackendRequest) (response ocilb.GetBackendResponse, err error)
	// GetBackendHealth(ctx context.Context, request ocilb.GetBackendHealthRequest) (response ocilb.GetBackendHealthResponse, err error)
	GetBackendSet(ctx context.Context, request ocilb.GetBackendSetRequest) (response ocilb.GetBackendSetResponse, err error)
	// health checker uses backendset crud operations
	// GetBackendSetHealth(ctx context.Context, request ocilb.GetBackendSetHealthRequest) (response ocilb.GetBackendSetHealthResponse, err error)
	// GetHealthChecker(ctx context.Context, request ocilb.GetHealthCheckerRequest) (response ocilb.GetHealthCheckerResponse, err error)
	GetLoadBalancer(ctx context.Context, request ocilb.GetLoadBalancerRequest) (response ocilb.GetLoadBalancerResponse, err error)
	// GetLoadBalancerHealth(ctx context.Context, request ocilb.GetLoadBalancerHealthRequest) (response ocilb.GetLoadBalancerHealthResponse, err error)
	// GetPathRouteSet(ctx context.Context, request ocilb.GetPathRouteSetRequest) (response ocilb.GetPathRouteSetResponse, err error)
	GetWorkRequest(ctx context.Context, request ocilb.GetWorkRequestRequest) (response ocilb.GetWorkRequestResponse, err error)
	// ListBackendSets(ctx context.Context, request ocilb.ListBackendSetsRequest) (response ocilb.ListBackendSetsResponse, err error)
	// ListBackends(ctx context.Context, request ocilb.ListBackendsRequest) (response ocilb.ListBackendsResponse, err error)
	// ListCertificates(ctx context.Context, request ocilb.ListCertificatesRequest) (response ocilb.ListCertificatesResponse, err error)
	// ListLoadBalancerHealths(ctx context.Context, request ocilb.ListLoadBalancerHealthsRequest) (response ocilb.ListLoadBalancerHealthsResponse, err error)
	// ListLoadBalancers(ctx context.Context, request ocilb.ListLoadBalancersRequest) (response ocilb.ListLoadBalancersResponse, err error)
	// ListPathRouteSets(ctx context.Context, request ocilb.ListPathRouteSetsRequest) (response ocilb.ListPathRouteSetsResponse, err error)
	// ListPolicies(ctx context.Context, request ocilb.ListPoliciesRequest) (response ocilb.ListPoliciesResponse, err error)
	// ListProtocols(ctx context.Context, request ocilb.ListProtocolsRequest) (response ocilb.ListProtocolsResponse, err error)
	// ListShapes(ctx context.Context, request ocilb.ListShapesRequest) (response ocilb.ListShapesResponse, err error)
	// ListWorkRequests(ctx context.Context, request ocilb.ListWorkRequestsRequest) (response ocilb.ListWorkRequestsResponse, err error)
	UpdateBackend(ctx context.Context, request ocilb.UpdateBackendRequest) (response ocilb.UpdateBackendResponse, err error)
	UpdateBackendSet(ctx context.Context, request ocilb.UpdateBackendSetRequest) (response ocilb.UpdateBackendSetResponse, err error)
	// UpdateHealthChecker(ctx context.Context, request ocilb.UpdateHealthCheckerRequest) (response ocilb.UpdateHealthCheckerResponse, err error)
	UpdateListener(ctx context.Context, request ocilb.UpdateListenerRequest) (response ocilb.UpdateListenerResponse, err error)
	UpdateLoadBalancer(ctx context.Context, request ocilb.UpdateLoadBalancerRequest) (response ocilb.UpdateLoadBalancerResponse, err error)
	// UpdatePathRouteSet(ctx context.Context, request ocilb.UpdatePathRouteSetRequest) (response ocilb.UpdatePathRouteSetResponse, err error)
}

// VcnClientInterface defines an interface for the oci vcn client to be implemented by real and fake clients
type VcnClientInterface interface {
	// BulkAddVirtualCircuitPublicPrefixes(ctx context.Context, request ocicore.BulkAddVirtualCircuitPublicPrefixesRequest) (err error)
	// BulkDeleteVirtualCircuitPublicPrefixes(ctx context.Context, request ocicore.BulkDeleteVirtualCircuitPublicPrefixesRequest) (err error)
	// ConnectLocalPeeringGateways(ctx context.Context, request ocicore.ConnectLocalPeeringGatewaysRequest) (response ocicore.ConnectLocalPeeringGatewaysResponse, err error)
	// ConnectRemotePeeringConnections(ctx context.Context, request ocicore.ConnectRemotePeeringConnectionsRequest) (response ocicore.ConnectRemotePeeringConnectionsResponse, err error)
	// CreateCpe(ctx context.Context, request ocicore.CreateCpeRequest) (response ocicore.CreateCpeResponse, err error)
	// CreateCrossConnect(ctx context.Context, request ocicore.CreateCrossConnectRequest) (response ocicore.CreateCrossConnectResponse, err error)
	// CreateCrossConnectGroup(ctx context.Context, request ocicore.CreateCrossConnectGroupRequest) (response ocicore.CreateCrossConnectGroupResponse, err error)
	CreateDhcpOptions(ctx context.Context, request ocicore.CreateDhcpOptionsRequest) (response ocicore.CreateDhcpOptionsResponse, err error)
	// CreateDrg(ctx context.Context, request ocicore.CreateDrgRequest) (response ocicore.CreateDrgResponse, err error)
	// CreateDrgAttachment(ctx context.Context, request ocicore.CreateDrgAttachmentRequest) (response ocicore.CreateDrgAttachmentResponse, err error)
	// CreateIPSecConnection(ctx context.Context, request ocicore.CreateIPSecConnectionRequest) (response ocicore.CreateIPSecConnectionResponse, err error)
	CreateInternetGateway(ctx context.Context, request ocicore.CreateInternetGatewayRequest) (response ocicore.CreateInternetGatewayResponse, err error)
	// CreateLocalPeeringGateway(ctx context.Context, request ocicore.CreateLocalPeeringGatewayRequest) (response ocicore.CreateLocalPeeringGatewayResponse, err error)
	// CreatePrivateIp(ctx context.Context, request ocicore.CreatePrivateIpRequest) (response ocicore.CreatePrivateIpResponse, err error)
	// CreatePublicIp(ctx context.Context, request ocicore.CreatePublicIpRequest) (response ocicore.CreatePublicIpResponse, err error)
	// CreateRemotePeeringConnection(ctx context.Context, request ocicore.CreateRemotePeeringConnectionRequest) (response ocicore.CreateRemotePeeringConnectionResponse, err error)
	CreateRouteTable(ctx context.Context, request ocicore.CreateRouteTableRequest) (response ocicore.CreateRouteTableResponse, err error)
	CreateSecurityList(ctx context.Context, request ocicore.CreateSecurityListRequest) (response ocicore.CreateSecurityListResponse, err error)
	CreateSubnet(ctx context.Context, request ocicore.CreateSubnetRequest) (response ocicore.CreateSubnetResponse, err error)
	CreateVcn(ctx context.Context, request ocicore.CreateVcnRequest) (response ocicore.CreateVcnResponse, err error)
	// CreateVirtualCircuit(ctx context.Context, request ocicore.CreateVirtualCircuitRequest) (response ocicore.CreateVirtualCircuitResponse, err error)
	// DeleteCpe(ctx context.Context, request ocicore.DeleteCpeRequest) (response ocicore.DeleteCpeResponse, err error)
	// DeleteCrossConnect(ctx context.Context, request ocicore.DeleteCrossConnectRequest) (response ocicore.DeleteCrossConnectResponse, err error)
	// DeleteCrossConnectGroup(ctx context.Context, request ocicore.DeleteCrossConnectGroupRequest) (response ocicore.DeleteCrossConnectGroupResponse, err error)
	DeleteDhcpOptions(ctx context.Context, request ocicore.DeleteDhcpOptionsRequest) (response ocicore.DeleteDhcpOptionsResponse, err error)
	// DeleteDrg(ctx context.Context, request ocicore.DeleteDrgRequest) (response ocicore.DeleteDrgResponse, err error)
	// DeleteDrgAttachment(ctx context.Context, request ocicore.DeleteDrgAttachmentRequest) (response ocicore.DeleteDrgAttachmentResponse, err error)
	// DeleteIPSecConnection(ctx context.Context, request ocicore.DeleteIPSecConnectionRequest) (response ocicore.DeleteIPSecConnectionResponse, err error)
	DeleteInternetGateway(ctx context.Context, request ocicore.DeleteInternetGatewayRequest) (response ocicore.DeleteInternetGatewayResponse, err error)
	// DeleteLocalPeeringGateway(ctx context.Context, request ocicore.DeleteLocalPeeringGatewayRequest) (response ocicore.DeleteLocalPeeringGatewayResponse, err error)
	// DeletePrivateIp(ctx context.Context, request ocicore.DeletePrivateIpRequest) (response ocicore.DeletePrivateIpResponse, err error)
	// DeletePublicIp(ctx context.Context, request ocicore.DeletePublicIpRequest) (response ocicore.DeletePublicIpResponse, err error)
	// DeleteRemotePeeringConnection(ctx context.Context, request ocicore.DeleteRemotePeeringConnectionRequest) (response ocicore.DeleteRemotePeeringConnectionResponse, err error)
	DeleteRouteTable(ctx context.Context, request ocicore.DeleteRouteTableRequest) (response ocicore.DeleteRouteTableResponse, err error)
	DeleteSecurityList(ctx context.Context, request ocicore.DeleteSecurityListRequest) (response ocicore.DeleteSecurityListResponse, err error)
	DeleteSubnet(ctx context.Context, request ocicore.DeleteSubnetRequest) (response ocicore.DeleteSubnetResponse, err error)
	DeleteVcn(ctx context.Context, request ocicore.DeleteVcnRequest) (response ocicore.DeleteVcnResponse, err error)
	// DeleteVirtualCircuit(ctx context.Context, request ocicore.DeleteVirtualCircuitRequest) (response ocicore.DeleteVirtualCircuitResponse, err error)
	// GetCpe(ctx context.Context, request ocicore.GetCpeRequest) (response ocicore.GetCpeResponse, err error)
	// GetCrossConnect(ctx context.Context, request ocicore.GetCrossConnectRequest) (response ocicore.GetCrossConnectResponse, err error)
	// GetCrossConnectGroup(ctx context.Context, request ocicore.GetCrossConnectGroupRequest) (response ocicore.GetCrossConnectGroupResponse, err error)
	// GetCrossConnectLetterOfAuthority(ctx context.Context, request ocicore.GetCrossConnectLetterOfAuthorityRequest) (response ocicore.GetCrossConnectLetterOfAuthorityResponse, err error)
	// GetCrossConnectStatus(ctx context.Context, request ocicore.GetCrossConnectStatusRequest) (response ocicore.GetCrossConnectStatusResponse, err error)
	GetDhcpOptions(ctx context.Context, request ocicore.GetDhcpOptionsRequest) (response ocicore.GetDhcpOptionsResponse, err error)
	// GetDrg(ctx context.Context, request ocicore.GetDrgRequest) (response ocicore.GetDrgResponse, err error)
	// GetDrgAttachment(ctx context.Context, request ocicore.GetDrgAttachmentRequest) (response ocicore.GetDrgAttachmentResponse, err error)
	// GetFastConnectProviderService(ctx context.Context, request ocicore.GetFastConnectProviderServiceRequest) (response ocicore.GetFastConnectProviderServiceResponse, err error)
	// GetIPSecConnection(ctx context.Context, request ocicore.GetIPSecConnectionRequest) (response ocicore.GetIPSecConnectionResponse, err error)
	// GetIPSecConnectionDeviceConfig(ctx context.Context, request ocicore.GetIPSecConnectionDeviceConfigRequest) (response ocicore.GetIPSecConnectionDeviceConfigResponse, err error)
	// GetIPSecConnectionDeviceStatus(ctx context.Context, request ocicore.GetIPSecConnectionDeviceStatusRequest) (response ocicore.GetIPSecConnectionDeviceStatusResponse, err error)
	GetInternetGateway(ctx context.Context, request ocicore.GetInternetGatewayRequest) (response ocicore.GetInternetGatewayResponse, err error)
	// GetLocalPeeringGateway(ctx context.Context, request ocicore.GetLocalPeeringGatewayRequest) (response ocicore.GetLocalPeeringGatewayResponse, err error)
	// GetPrivateIp(ctx context.Context, request ocicore.GetPrivateIpRequest) (response ocicore.GetPrivateIpResponse, err error)
	// GetPublicIp(ctx context.Context, request ocicore.GetPublicIpRequest) (response ocicore.GetPublicIpResponse, err error)
	// GetPublicIpByIpAddress(ctx context.Context, request ocicore.GetPublicIpByIpAddressRequest) (response ocicore.GetPublicIpByIpAddressResponse, err error)
	// GetPublicIpByPrivateIpId(ctx context.Context, request ocicore.GetPublicIpByPrivateIpIdRequest) (response ocicore.GetPublicIpByPrivateIpIdResponse, err error)
	// GetRemotePeeringConnection(ctx context.Context, request ocicore.GetRemotePeeringConnectionRequest) (response ocicore.GetRemotePeeringConnectionResponse, err error)
	GetRouteTable(ctx context.Context, request ocicore.GetRouteTableRequest) (response ocicore.GetRouteTableResponse, err error)
	GetSecurityList(ctx context.Context, request ocicore.GetSecurityListRequest) (response ocicore.GetSecurityListResponse, err error)
	GetSubnet(ctx context.Context, request ocicore.GetSubnetRequest) (response ocicore.GetSubnetResponse, err error)
	GetVcn(ctx context.Context, request ocicore.GetVcnRequest) (response ocicore.GetVcnResponse, err error)
	// GetVirtualCircuit(ctx context.Context, request ocicore.GetVirtualCircuitRequest) (response ocicore.GetVirtualCircuitResponse, err error)
	GetVnic(ctx context.Context, request ocicore.GetVnicRequest) (response ocicore.GetVnicResponse, err error)
	// ListAllowedPeerRegionsForRemotePeering(ctx context.Context, request ocicore.ListAllowedPeerRegionsForRemotePeeringRequest) (response ocicore.ListAllowedPeerRegionsForRemotePeeringResponse, err error)
	// ListCpes(ctx context.Context, request ocicore.ListCpesRequest) (response ocicore.ListCpesResponse, err error)
	// ListCrossConnectGroups(ctx context.Context, request ocicore.ListCrossConnectGroupsRequest) (response ocicore.ListCrossConnectGroupsResponse, err error)
	// ListCrossConnectLocations(ctx context.Context, request ocicore.ListCrossConnectLocationsRequest) (response ocicore.ListCrossConnectLocationsResponse, err error)
	// ListCrossConnects(ctx context.Context, request ocicore.ListCrossConnectsRequest) (response ocicore.ListCrossConnectsResponse, err error)
	// ListCrossconnectPortSpeedShapes(ctx context.Context, request ocicore.ListCrossconnectPortSpeedShapesRequest) (response ocicore.ListCrossconnectPortSpeedShapesResponse, err error)
	// ListDhcpOptions(ctx context.Context, request ocicore.ListDhcpOptionsRequest) (response ocicore.ListDhcpOptionsResponse, err error)
	// ListDrgAttachments(ctx context.Context, request ocicore.ListDrgAttachmentsRequest) (response ocicore.ListDrgAttachmentsResponse, err error)
	// ListDrgs(ctx context.Context, request ocicore.ListDrgsRequest) (response ocicore.ListDrgsResponse, err error)
	// ListFastConnectProviderServices(ctx context.Context, request ocicore.ListFastConnectProviderServicesRequest) (response ocicore.ListFastConnectProviderServicesResponse, err error)
	// ListFastConnectProviderVirtualCircuitBandwidthShapes(ctx context.Context, request ocicore.ListFastConnectProviderVirtualCircuitBandwidthShapesRequest) (response ocicore.ListFastConnectProviderVirtualCircuitBandwidthShapesResponse, err error)
	// ListIPSecConnections(ctx context.Context, request ocicore.ListIPSecConnectionsRequest) (response ocicore.ListIPSecConnectionsResponse, err error)
	// ListInternetGateways(ctx context.Context, request ocicore.ListInternetGatewaysRequest) (response ocicore.ListInternetGatewaysResponse, err error)
	// ListLocalPeeringGateways(ctx context.Context, request ocicore.ListLocalPeeringGatewaysRequest) (response ocicore.ListLocalPeeringGatewaysResponse, err error)
	// ListPrivateIps(ctx context.Context, request ocicore.ListPrivateIpsRequest) (response ocicore.ListPrivateIpsResponse, err error)
	// ListPublicIps(ctx context.Context, request ocicore.ListPublicIpsRequest) (response ocicore.ListPublicIpsResponse, err error)
	// ListRemotePeeringConnections(ctx context.Context, request ocicore.ListRemotePeeringConnectionsRequest) (response ocicore.ListRemotePeeringConnectionsResponse, err error)
	// ListRouteTables(ctx context.Context, request ocicore.ListRouteTablesRequest) (response ocicore.ListRouteTablesResponse, err error)
	// ListSecurityLists(ctx context.Context, request ocicore.ListSecurityListsRequest) (response ocicore.ListSecurityListsResponse, err error)
	// ListSubnets(ctx context.Context, request ocicore.ListSubnetsRequest) (response ocicore.ListSubnetsResponse, err error)
	// ListVcns(ctx context.Context, request ocicore.ListVcnsRequest) (response ocicore.ListVcnsResponse, err error)
	// ListVirtualCircuitBandwidthShapes(ctx context.Context, request ocicore.ListVirtualCircuitBandwidthShapesRequest) (response ocicore.ListVirtualCircuitBandwidthShapesResponse, err error)
	// ListVirtualCircuitPublicPrefixes(ctx context.Context, request ocicore.ListVirtualCircuitPublicPrefixesRequest) (response ocicore.ListVirtualCircuitPublicPrefixesResponse, err error)
	// ListVirtualCircuits(ctx context.Context, request ocicore.ListVirtualCircuitsRequest) (response ocicore.ListVirtualCircuitsResponse, err error)
	// UpdateCpe(ctx context.Context, request ocicore.UpdateCpeRequest) (response ocicore.UpdateCpeResponse, err error)
	// UpdateCrossConnect(ctx context.Context, request ocicore.UpdateCrossConnectRequest) (response ocicore.UpdateCrossConnectResponse, err error)
	// UpdateCrossConnectGroup(ctx context.Context, request ocicore.UpdateCrossConnectGroupRequest) (response ocicore.UpdateCrossConnectGroupResponse, err error)
	UpdateDhcpOptions(ctx context.Context, request ocicore.UpdateDhcpOptionsRequest) (response ocicore.UpdateDhcpOptionsResponse, err error)
	// UpdateDrg(ctx context.Context, request ocicore.UpdateDrgRequest) (response ocicore.UpdateDrgResponse, err error)
	// UpdateDrgAttachment(ctx context.Context, request ocicore.UpdateDrgAttachmentRequest) (response ocicore.UpdateDrgAttachmentResponse, err error)
	// UpdateIPSecConnection(ctx context.Context, request ocicore.UpdateIPSecConnectionRequest) (response ocicore.UpdateIPSecConnectionResponse, err error)
	UpdateInternetGateway(ctx context.Context, request ocicore.UpdateInternetGatewayRequest) (response ocicore.UpdateInternetGatewayResponse, err error)
	// UpdateLocalPeeringGateway(ctx context.Context, request ocicore.UpdateLocalPeeringGatewayRequest) (response ocicore.UpdateLocalPeeringGatewayResponse, err error)
	// UpdatePrivateIp(ctx context.Context, request ocicore.UpdatePrivateIpRequest) (response ocicore.UpdatePrivateIpResponse, err error)
	// UpdatePublicIp(ctx context.Context, request ocicore.UpdatePublicIpRequest) (response ocicore.UpdatePublicIpResponse, err error)
	// UpdateRemotePeeringConnection(ctx context.Context, request ocicore.UpdateRemotePeeringConnectionRequest) (response ocicore.UpdateRemotePeeringConnectionResponse, err error)
	UpdateRouteTable(ctx context.Context, request ocicore.UpdateRouteTableRequest) (response ocicore.UpdateRouteTableResponse, err error)
	UpdateSecurityList(ctx context.Context, request ocicore.UpdateSecurityListRequest) (response ocicore.UpdateSecurityListResponse, err error)
	UpdateSubnet(ctx context.Context, request ocicore.UpdateSubnetRequest) (response ocicore.UpdateSubnetResponse, err error)
	UpdateVcn(ctx context.Context, request ocicore.UpdateVcnRequest) (response ocicore.UpdateVcnResponse, err error)
	// UpdateVirtualCircuit(ctx context.Context, request ocicore.UpdateVirtualCircuitRequest) (response ocicore.UpdateVirtualCircuitResponse, err error)
	// UpdateVnic(ctx context.Context, request ocicore.UpdateVnicRequest) (response ocicore.UpdateVnicResponse, err error)
}
